name: crafter-appo-baseline

global_settings:
  use_wandb: True
  experiment: CrafterBaseline

experiment_settings:
  save_every_sec: 120
  train_for_env_steps: 100000000
  hidden_size: 512
  learning_rate: 0.0001

async_ppo:

  experiment_summaries_interval: 5
  ppo_epochs: 1
  batch_size: 1024
  adam_eps: 0.00001

  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 8
  num_envs_per_worker: 20

environment:
  name: "CrafterReward-v1"